# -*- coding: utf-8 -*-
"""OcclusionPoseNet_v5_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1irYyXCyropIxzDyBiFqejFLYwdDaIoH4

# OcclusionPoseNet v5 — Advanced Smart Pipeline
## Object Completion (U-Net) + Pose Estimation (Vision Transformer)
### v3 format | 30K samples | AMP training | Smart routing | Full evaluation
---
> **Runtime → Change Runtime Type → T4 GPU** before running!

### What is new in v5 vs v3.1:
| Feature | v3.1 | v5 |
|---|---|---|
| U-Net activation | ReLU | GELU (smoother gradients) |
| ViT head | 2-layer | 3-layer deeper head |
| Gradient clipping | No | Yes (max norm 1.0) |
| Confusion matrix | Blues only | Multi-colour per class |
| Training graphs | Basic | Annotated with best epoch |
| Checkpoint names | unet_best.pth | unet_v5_best.pth (no conflict) |
| Demo output | File path | PIL image (Gradio 5.x fixed) |
| Force occlusion | No | Yes + slider in demo |

## STEP 1 — Install Dependencies
"""

!pip install torch torchvision timm 'gradio==5.50.0' scikit-image matplotlib Pillow tqdm einops opencv-python -q
print('All packages installed')

"""## STEP 2 — Create Project Folders"""

import os
for d in ['models','utils','demo','checkpoints','results']:
    os.makedirs(d, exist_ok=True)
print('Folders created')

"""## STEP 3 — Write Model Files"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/__init__.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/unet.py
# import torch, torch.nn as nn, torch.nn.functional as F
# 
# class ConvBlock(nn.Module):
#     def __init__(self, ic, oc):
#         super().__init__()
#         self.b = nn.Sequential(
#             nn.Conv2d(ic, oc, 3, padding=1), nn.BatchNorm2d(oc), nn.GELU(),
#             nn.Conv2d(oc, oc, 3, padding=1), nn.BatchNorm2d(oc), nn.GELU())
#     def forward(self, x): return self.b(x)
# 
# class UNet(nn.Module):
#     def __init__(self, in_c=3, out_c=3, feats=(64,128,256,512)):
#         super().__init__()
#         self.encs = nn.ModuleList()
#         self.pool = nn.MaxPool2d(2)
#         self.ups  = nn.ModuleList()
#         self.decs = nn.ModuleList()
#         c = in_c
#         for f in feats:
#             self.encs.append(ConvBlock(c, f)); c = f
#         self.neck = ConvBlock(feats[-1], feats[-1]*2)
#         prev = feats[-1]*2
#         for f in reversed(feats):
#             self.ups.append(nn.ConvTranspose2d(prev, f, 2, 2))
#             self.decs.append(ConvBlock(f*2, f))
#             prev = f
#         self.head = nn.Sequential(nn.Conv2d(feats[0], out_c, 1), nn.Sigmoid())
# 
#     def forward(self, x):
#         skips = []
#         for e in self.encs:
#             x = e(x); skips.append(x); x = self.pool(x)
#         x = self.neck(x)
#         for up, dec, sk in zip(self.ups, self.decs, reversed(skips)):
#             x = up(x)
#             if x.shape != sk.shape:
#                 x = F.interpolate(x, size=sk.shape[2:])
#             x = dec(torch.cat([sk, x], 1))
#         return self.head(x)
# 
# print('models/unet.py written')

# Commented out IPython magic to ensure Python compatibility.
# %%writefile models/vit_pose.py
# import torch.nn as nn, timm
# 
# class ViTPoseNet(nn.Module):
#     def __init__(self, num_classes=4, pretrained=True):
#         super().__init__()
#         self.vit = timm.create_model('vit_small_patch16_224',
#                                      pretrained=pretrained, num_classes=0)
#         emb = self.vit.embed_dim
#         self.head = nn.Sequential(
#             nn.LayerNorm(emb),
#             nn.Linear(emb, 256), nn.GELU(), nn.Dropout(0.3),
#             nn.Linear(256, 128), nn.GELU(), nn.Dropout(0.2),
#             nn.Linear(128, num_classes))
# 
#     def forward(self, x): return self.head(self.vit(x))
# 
# print('models/vit_pose.py written')

"""## STEP 4 — Dataset Loader (30K subset, CIFAR stats, 8-60% occlusion)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile utils/__init__.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile utils/dataset_loader.py
# import os, random
# import torch
# from torch.utils.data import Dataset, ConcatDataset, Subset
# import torchvision, torchvision.transforms as T
# from PIL import Image, ImageDraw
# 
# POSE_DEGREES = [0, 90, 180, 270]
# POSE_MAP     = {0:0, 90:1, 180:2, 270:3}
# IMG_SIZE     = 128
# MEAN         = [0.4914, 0.4822, 0.4465]
# STD          = [0.2023, 0.1994, 0.2010]
# 
# def apply_occlusion(img_pil, min_pct=0.08, max_pct=0.60):
#     img  = img_pil.copy()
#     draw = ImageDraw.Draw(img)
#     w, h = img.size
#     target  = random.uniform(min_pct, max_pct) * w * h
#     covered = 0
#     while covered < target:
#         bw = random.randint(int(w*0.05), int(w*0.40))
#         bh = random.randint(int(h*0.05), int(h*0.40))
#         x1 = random.randint(0, max(0, w-bw))
#         y1 = random.randint(0, max(0, h-bh))
#         draw.rectangle([x1,y1,x1+bw,y1+bh], fill=(0,0,0))
#         covered += bw * bh
#     return img
# 
# class PoseOcclusionDataset(Dataset):
#     def __init__(self, base_dataset, img_size=IMG_SIZE, augment=True, mix_clean=False):
#         self.data      = base_dataset
#         self.size      = img_size
#         self.augment   = augment
#         self.mix_clean = mix_clean
#         self.to_pil    = T.ToPILImage()
#         self.norm = T.Compose([T.Resize((img_size,img_size)), T.ToTensor(),
#                                T.Normalize(MEAN, STD)])
#         self.raw  = T.Compose([T.Resize((img_size,img_size)), T.ToTensor()])
# 
#     def __len__(self): return len(self.data)
# 
#     def __getitem__(self, idx):
#         img, _ = self.data[idx]
#         if not isinstance(img, Image.Image):
#             img = self.to_pil(img)
#         img     = img.convert("RGB").resize((self.size, self.size))
#         deg     = random.choice(POSE_DEGREES)
#         rotated = img.rotate(deg)
#         if self.augment:
#             masked = rotated if (self.mix_clean and random.random()<0.40) else apply_occlusion(rotated)
#         else:
#             masked = rotated
#         return (self.norm(masked), self.raw(rotated),
#                 torch.tensor(POSE_MAP[deg], dtype=torch.long))
# 
# def get_combined_dataset(root="./data", split="train", mix_clean=False, subset=30000):
#     train   = (split == "train")
#     base_tf = T.Compose([T.ToTensor()])
#     c10  = torchvision.datasets.CIFAR10 (root=root, train=train, download=True, transform=base_tf)
#     c100 = torchvision.datasets.CIFAR100(root=root, train=train, download=True, transform=base_tf)
#     stl  = torchvision.datasets.STL10   (root=root, split="train" if train else "test",
#                                           download=True, transform=base_tf)
#     combined = ConcatDataset([c10, c100, stl])
#     if subset and len(combined) > subset:
#         idx      = torch.randperm(len(combined),
#                        generator=torch.Generator().manual_seed(42))[:subset].tolist()
#         combined = Subset(combined, idx)
#     return PoseOcclusionDataset(combined, mix_clean=mix_clean)
# 
# print("utils/dataset_loader.py written")

"""## STEP 5 — Write Training Scripts (AMP + AdamW + Gradient Clipping)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_completion.py
# import torch, torch.nn as nn
# from torch.utils.data import DataLoader, random_split
# from models.unet import UNet
# from utils.dataset_loader import get_combined_dataset
# from tqdm import tqdm
# import json, os
# 
# DEVICE   = "cuda" if torch.cuda.is_available() else "cpu"
# EPOCHS   = 15
# LR       = 1e-3
# BATCH    = 128
# PATIENCE = 4
# print(f"Device: {DEVICE}")
# 
# full_ds  = get_combined_dataset("./data", "train", mix_clean=False, subset=30000)
# n_val    = int(len(full_ds) * 0.10)
# train_ds, val_ds = random_split(full_ds, [len(full_ds)-n_val, n_val],
#                                 generator=torch.Generator().manual_seed(42))
# train_loader = DataLoader(train_ds, batch_size=BATCH, shuffle=True,  num_workers=2, pin_memory=True)
# val_loader   = DataLoader(val_ds,   batch_size=BATCH, shuffle=False, num_workers=2, pin_memory=True)
# print(f"Train: {len(train_ds):,} | Val: {len(val_ds):,} | Batches/epoch: {len(train_loader)}")
# 
# model  = UNet().to(DEVICE)
# opt    = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
# sched  = torch.optim.lr_scheduler.OneCycleLR(opt, max_lr=LR,
#              steps_per_epoch=len(train_loader), epochs=EPOCHS)
# l1_fn  = nn.L1Loss()
# mse_fn = nn.MSELoss()
# scaler = torch.cuda.amp.GradScaler()
# 
# best_val = float("inf"); patience_ctr = 0
# history  = {"train": [], "val": []}
# 
# for ep in range(EPOCHS):
#     model.train(); tot = 0
#     for masked, orig, _ in tqdm(train_loader, desc=f"Ep {ep+1}/{EPOCHS} [U-Net]"):
#         masked, orig = masked.to(DEVICE), orig.to(DEVICE)
#         opt.zero_grad()
#         with torch.cuda.amp.autocast():
#             pred = model(masked)
#             loss = l1_fn(pred, orig) + 0.5 * mse_fn(pred, orig)
#         scaler.scale(loss).backward()
#         scaler.unscale_(opt)
#         torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
#         scaler.step(opt); scaler.update(); sched.step()
#         tot += loss.item()
# 
#     model.eval(); vl = 0
#     with torch.no_grad():
#         for masked, orig, _ in val_loader:
#             masked, orig = masked.to(DEVICE), orig.to(DEVICE)
#             with torch.cuda.amp.autocast():
#                 pred = model(masked)
#                 vl  += (l1_fn(pred, orig) + 0.5*mse_fn(pred, orig)).item()
# 
#     t_avg = tot/len(train_loader); v_avg = vl/len(val_loader)
#     history["train"].append(t_avg); history["val"].append(v_avg)
#     print(f"Epoch {ep+1:02d} | Train: {t_avg:.4f} | Val: {v_avg:.4f}", end="")
#     if v_avg < best_val:
#         best_val = v_avg; patience_ctr = 0
#         torch.save(model.state_dict(), "checkpoints/unet_v5_best.pth")
#         print(" saved")
#     else:
#         patience_ctr += 1
#         print(f" (patience {patience_ctr}/{PATIENCE})")
#         if patience_ctr >= PATIENCE:
#             print(f"Early stopping at epoch {ep+1}"); break
# 
# os.makedirs("results", exist_ok=True)
# json.dump(history, open("results/unet_history.json","w"))
# print(f"U-Net done! Best Val Loss: {best_val:.4f}")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile train_posevit.py
# import torch, torch.nn as nn, torch.nn.functional as F
# from torch.utils.data import DataLoader, random_split
# from models.unet import UNet
# from models.vit_pose import ViTPoseNet
# from utils.dataset_loader import get_combined_dataset
# from tqdm import tqdm
# import json, os
# 
# DEVICE   = "cuda" if torch.cuda.is_available() else "cpu"
# EPOCHS   = 12
# LR       = 3e-4
# BATCH    = 64
# PATIENCE = 3
# MEAN = torch.tensor([0.4914,0.4822,0.4465]).view(1,3,1,1)
# STD  = torch.tensor([0.2023,0.1994,0.2010]).view(1,3,1,1)
# print(f"Device: {DEVICE}")
# 
# full_ds  = get_combined_dataset("./data", "train", mix_clean=True, subset=30000)
# n_val    = int(len(full_ds)*0.10)
# train_ds, val_ds = random_split(full_ds,[len(full_ds)-n_val,n_val],
#                                 generator=torch.Generator().manual_seed(42))
# train_loader = DataLoader(train_ds, BATCH, shuffle=True,  num_workers=2, pin_memory=True)
# val_loader   = DataLoader(val_ds,   BATCH, shuffle=False, num_workers=2, pin_memory=True)
# 
# unet = UNet().to(DEVICE)
# unet.load_state_dict(torch.load("checkpoints/unet_v5_best.pth", map_location=DEVICE))
# unet.eval()
# for p in unet.parameters(): p.requires_grad = False
# print("U-Net frozen")
# 
# vit = ViTPoseNet(num_classes=4, pretrained=True).to(DEVICE)
# for p in vit.vit.parameters(): p.requires_grad = False
# for name, p in vit.vit.named_parameters():
#     if any(f"blocks.{i}" in name for i in [8,9,10,11]):
#         p.requires_grad = True
# for p in vit.head.parameters(): p.requires_grad = True
# trainable = sum(p.numel() for p in vit.parameters() if p.requires_grad)
# print(f"ViT loaded | Trainable params: {trainable:,}")
# 
# opt    = torch.optim.AdamW(filter(lambda p:p.requires_grad, vit.parameters()),
#                             lr=LR, weight_decay=1e-2)
# sched  = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=EPOCHS)
# crit   = nn.CrossEntropyLoss(label_smoothing=0.1)
# scaler = torch.cuda.amp.GradScaler()
# 
# best_acc = 0; patience_ctr = 0
# history  = {"train_acc":[], "val_acc":[]}
# 
# for ep in range(EPOCHS):
#     vit.train(); correct = total_n = 0
#     for masked, orig, labels in tqdm(train_loader, desc=f"Ep {ep+1}/{EPOCHS} [ViT]"):
#         masked, labels = masked.to(DEVICE), labels.to(DEVICE)
#         with torch.no_grad():
#             recon = unet(masked)
#         opt.zero_grad()
#         with torch.cuda.amp.autocast():
#             r224   = F.interpolate(recon, 224, mode="bilinear", align_corners=False)
#             r_norm = (r224 - MEAN.to(DEVICE)) / STD.to(DEVICE)
#             logits = vit(r_norm)
#             loss   = crit(logits, labels)
#         scaler.scale(loss).backward()
#         scaler.unscale_(opt)
#         torch.nn.utils.clip_grad_norm_(
#             filter(lambda p:p.requires_grad, vit.parameters()), 1.0)
#         scaler.step(opt); scaler.update()
#         correct  += (logits.argmax(1)==labels).sum().item()
#         total_n  += labels.size(0)
# 
#     vit.eval(); vc = vt = 0
#     with torch.no_grad():
#         for masked, orig, labels in val_loader:
#             masked, labels = masked.to(DEVICE), labels.to(DEVICE)
#             recon  = unet(masked)
#             r224   = F.interpolate(recon,224,mode="bilinear",align_corners=False)
#             r_norm = (r224 - MEAN.to(DEVICE)) / STD.to(DEVICE)
#             with torch.cuda.amp.autocast():
#                 logits = vit(r_norm)
#             vc += (logits.argmax(1)==labels).sum().item()
#             vt += labels.size(0)
# 
#     sched.step()
#     t_acc = 100*correct/total_n; v_acc = 100*vc/vt
#     history["train_acc"].append(t_acc); history["val_acc"].append(v_acc)
#     print(f"Epoch {ep+1:02d} | Train: {t_acc:.2f}% | Val: {v_acc:.2f}%", end="")
#     if v_acc > best_acc:
#         best_acc = v_acc; patience_ctr = 0
#         torch.save(vit.state_dict(), "checkpoints/vit_pose_v5_best.pth")
#         print(f" Best ({best_acc:.2f}%)")
#     else:
#         patience_ctr += 1
#         print(f" (patience {patience_ctr}/{PATIENCE})")
#         if patience_ctr >= PATIENCE:
#             print(f"Early stopping at epoch {ep+1}"); break
# 
# os.makedirs("results", exist_ok=True)
# json.dump(history, open("results/vit_history.json","w"))
# print(f"ViT done! Best Val Acc: {best_acc:.2f}%")

"""## STEP 6 — Download Datasets (30K train, 5K test)"""

from utils.dataset_loader import get_combined_dataset
train_ds = get_combined_dataset('./data','train', subset=30000)
test_ds  = get_combined_dataset('./data','test',  subset=5000)
print(f'Train: {len(train_ds):,} | Test: {len(test_ds):,}')

"""## STEP 7 — Sanity Check: Visualise Dataset Samples"""

import matplotlib.pyplot as plt
import torchvision.transforms as T

to_pil      = T.ToPILImage()
POSE_LABELS = ['0 Upright','90 Rotated','180 Inverted','270 Rotated']

fig, axes = plt.subplots(3, 6, figsize=(15,7), facecolor='#0d1117')
for col in range(6):
    masked, orig, label = train_ds[col*300]
    for row, (img, title) in enumerate([
        (masked, f'Masked {POSE_LABELS[label]}'),
        (orig,   'Original'),
        ((masked-orig).abs()*3, 'Occlusion Mask'),
    ]):
        ax = axes[row][col]
        ax.set_facecolor('#161b22')
        ax.imshow(to_pil(img.clamp(0,1)))
        ax.set_title(title, color='#c9d1d9', fontsize=7, pad=3)
        ax.axis('off')

plt.suptitle('v5 Dataset — Row 1: Masked | Row 2: Ground Truth | Row 3: Occlusion Mask',
             color='white', fontsize=10)
plt.tight_layout(); plt.show()
print('Sanity check passed!')

"""## STEP 8 — Mount Google Drive (auto save and resume)
> Checkpoints found on Drive → loaded, training skipped.
> Not found → trains from scratch, saves automatically.
"""

from google.colab import drive
drive.mount('/content/drive')

import os, shutil

DRIVE_DIR = '/content/drive/MyDrive/OcclusionPoseNet_v5'
os.makedirs(f'{DRIVE_DIR}/checkpoints', exist_ok=True)
os.makedirs(f'{DRIVE_DIR}/results',     exist_ok=True)

FILES = {
    f'{DRIVE_DIR}/checkpoints/unet_v5_best.pth'     : 'checkpoints/unet_v5_best.pth',
    f'{DRIVE_DIR}/checkpoints/vit_pose_v5_best.pth' : 'checkpoints/vit_pose_v5_best.pth',
    f'{DRIVE_DIR}/results/unet_history.json'         : 'results/unet_history.json',
    f'{DRIVE_DIR}/results/vit_history.json'          : 'results/vit_history.json',
}
for src, dst in FILES.items():
    if os.path.exists(src):
        shutil.copy(src, dst)
        print(f'Restored from Drive: {os.path.basename(dst)}')
    else:
        print(f'Not on Drive yet: {os.path.basename(src)} will train')

"""## STEP 9 — Train Stage 1: U-Net"""

# Commented out IPython magic to ensure Python compatibility.
import os, shutil

if os.path.exists('checkpoints/unet_v5_best.pth'):
    print('U-Net checkpoint found — skipping training!')
else:
    print('Training U-Net (~25 min)...')
#     %run train_completion.py
    shutil.copy('checkpoints/unet_v5_best.pth',
                '/content/drive/MyDrive/OcclusionPoseNet_v5/checkpoints/unet_v5_best.pth')
    shutil.copy('results/unet_history.json',
                '/content/drive/MyDrive/OcclusionPoseNet_v5/results/unet_history.json')
    print('U-Net saved to Google Drive!')

"""## STEP 10 — Train Stage 2: ViT Pose"""

# Commented out IPython magic to ensure Python compatibility.
import os, shutil

if os.path.exists('checkpoints/vit_pose_v5_best.pth'):
    print('ViT checkpoint found — skipping training!')
else:
    print('Training ViT (~55 min)...')
#     %run train_posevit.py
    shutil.copy('checkpoints/vit_pose_v5_best.pth',
                '/content/drive/MyDrive/OcclusionPoseNet_v5/checkpoints/vit_pose_v5_best.pth')
    shutil.copy('results/vit_history.json',
                '/content/drive/MyDrive/OcclusionPoseNet_v5/results/vit_history.json')
    print('ViT saved to Google Drive!')

"""## STEP 11 — Plot Training Curves (annotated with best epoch)"""

import json, matplotlib.pyplot as plt, numpy as np, os

fig, axes = plt.subplots(1, 2, figsize=(14,5), facecolor='#0d1117')

if os.path.exists('results/unet_history.json'):
    h  = json.load(open('results/unet_history.json'))
    ax = axes[0]; ax.set_facecolor('#161b22')
    ep = range(1, len(h['train'])+1)
    ax.plot(ep, h['train'], color='#58a6ff', lw=2.5, marker='o', ms=4, label='Train Loss')
    ax.plot(ep, h['val'],   color='#3fb950', lw=2.5, marker='s', ms=4, label='Val Loss')
    ax.fill_between(ep, h['val'], alpha=0.12, color='#3fb950')
    best_ep = int(np.argmin(h['val'])) + 1
    ax.axvline(x=best_ep, color='#ffa657', lw=1.5, ls='--', alpha=0.8)
    ax.text(best_ep+0.1, max(h['val'])*0.95, f'Best Ep {best_ep}', color='#ffa657', fontsize=8)
    ax.set_title('U-Net Completion Loss (v5)', color='white', fontsize=12, pad=8)
    ax.set_xlabel('Epoch', color='#8b949e'); ax.set_ylabel('L1+MSE Loss', color='#8b949e')
    ax.tick_params(colors='#8b949e')
    ax.legend(facecolor='#21262d', labelcolor='white', fontsize=9)
    for sp in ax.spines.values(): sp.set_color('#30363d')

if os.path.exists('results/vit_history.json'):
    h  = json.load(open('results/vit_history.json'))
    ax = axes[1]; ax.set_facecolor('#161b22')
    ep = range(1, len(h['train_acc'])+1)
    ax.plot(ep, h['train_acc'], color='#ffa657', lw=2.5, marker='o', ms=4, label='Train Acc')
    ax.plot(ep, h['val_acc'],   color='#3fb950', lw=2.5, marker='s', ms=4, label='Val Acc')
    ax.fill_between(ep, h['val_acc'], alpha=0.12, color='#3fb950')
    ax.axhline(y=90, color='#ff7b72', lw=1, ls='--', alpha=0.5, label='90% target')
    best_ep = int(np.argmax(h['val_acc'])) + 1
    ax.axvline(x=best_ep, color='#58a6ff', lw=1.5, ls='--', alpha=0.8)
    ax.text(best_ep+0.1, 5, f'Best Ep {best_ep}', color='#58a6ff', fontsize=8)
    ax.set_title('ViT Pose Accuracy (v5)', color='white', fontsize=12, pad=8)
    ax.set_xlabel('Epoch', color='#8b949e'); ax.set_ylabel('Accuracy (%)', color='#8b949e')
    ax.tick_params(colors='#8b949e'); ax.set_ylim(0,100)
    ax.legend(facecolor='#21262d', labelcolor='white', fontsize=9)
    for sp in ax.spines.values(): sp.set_color('#30363d')

fig.patch.set_facecolor('#0d1117')
plt.tight_layout(); plt.show()
print('Training curves plotted')

"""## STEP 12 — Full Evaluation (PSNR / SSIM / Pose Accuracy)"""

import torch, torch.nn.functional as F, numpy as np
import matplotlib.pyplot as plt
from torch.utils.data import DataLoader
from models.unet import UNet
from models.vit_pose import ViTPoseNet
from utils.dataset_loader import get_combined_dataset
from skimage.metrics import peak_signal_noise_ratio as psnr
from skimage.metrics import structural_similarity as ssim

DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
MEAN   = torch.tensor([0.4914,0.4822,0.4465]).view(1,3,1,1).to(DEVICE)
STD    = torch.tensor([0.2023,0.1994,0.2010]).view(1,3,1,1).to(DEVICE)
NAMES  = ['0 deg','90 deg','180 deg','270 deg']

unet = UNet().to(DEVICE)
vit  = ViTPoseNet(num_classes=4, pretrained=False).to(DEVICE)
unet.load_state_dict(torch.load('checkpoints/unet_v5_best.pth',     map_location=DEVICE))
vit.load_state_dict (torch.load('checkpoints/vit_pose_v5_best.pth', map_location=DEVICE))
unet.eval(); vit.eval()
print('Models loaded')

test_ds = get_combined_dataset('./data','test', subset=5000)
loader  = DataLoader(test_ds, batch_size=32, shuffle=False, num_workers=2)

psnr_list, ssim_list = [], []
cm = ct = rm = rt = 0
conf_mat = np.zeros((4,4), dtype=int)

with torch.no_grad():
    for masked, orig, labels in loader:
        masked, orig, labels = masked.to(DEVICE), orig.to(DEVICE), labels.to(DEVICE)
        recon = unet(masked)
        for i in range(orig.size(0)):
            o = orig [i].cpu().numpy().transpose(1,2,0)
            r = recon[i].clamp(0,1).cpu().numpy().transpose(1,2,0)
            psnr_list.append(psnr(o, r, data_range=1.0))
            ssim_list.append(ssim(o, r, data_range=1.0, channel_axis=2))
        m224 = F.interpolate(masked, 224, mode='bilinear', align_corners=False)
        lm   = vit((m224 - MEAN) / STD)
        cm  += (lm.argmax(1)==labels).sum().item(); ct += labels.size(0)
        r224 = F.interpolate(recon, 224, mode='bilinear', align_corners=False)
        lr   = vit((r224 - MEAN) / STD)
        rm  += (lr.argmax(1)==labels).sum().item(); rt += labels.size(0)
        for p_, t_ in zip(lr.argmax(1).cpu().numpy(), labels.cpu().numpy()):
            conf_mat[t_, p_] += 1

print(f'\nEvaluation Results:')
print(f'  PSNR                   : {np.mean(psnr_list):.2f} dB')
print(f'  SSIM                   : {np.mean(ssim_list):.4f}')
print(f'  Pose Acc - Masked      : {100*cm/ct:.2f}%')
print(f'  Pose Acc - Reconstructed: {100*rm/rt:.2f}%')
print(f'  Improvement            : +{100*rm/rt - 100*cm/ct:.2f}%')

"""## STEP 13 — Confusion Matrix"""

import numpy as np, matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from matplotlib.colors import LinearSegmentedColormap

NAMES = ['0 Upright','90 Rotated','180 Inverted','270 Rotated']

CLASS_CMAPS = [
    LinearSegmentedColormap.from_list('c0', ['#0d1117', '#58a6ff']),
    LinearSegmentedColormap.from_list('c1', ['#0d1117', '#3fb950']),
    LinearSegmentedColormap.from_list('c2', ['#0d1117', '#ffa657']),
    LinearSegmentedColormap.from_list('c3', ['#0d1117', '#f778ba']),
]

fig, axes = plt.subplots(1, 2, figsize=(14, 5), facecolor='#0d1117')

ax = axes[0]; ax.set_facecolor('#161b22')
cm_norm = conf_mat.astype(float) / conf_mat.sum(axis=1, keepdims=True).clip(1)
img_rgb = np.zeros((4, 4, 4))
for row in range(4):
    for col in range(4):
        img_rgb[row, col] = CLASS_CMAPS[row](cm_norm[row, col])

ax.imshow(img_rgb, aspect='auto')
for i in range(4):
    for j in range(4):
        val   = conf_mat[i, j]
        pct   = cm_norm[i, j] * 100
        color = '#0d1117' if cm_norm[i,j] > 0.5 else '#e6edf3'
        ax.text(j, i, f'{val}\n({pct:.1f}%)', ha='center', va='center',
                fontsize=9, color=color, fontweight='bold')

ax.set_xticks(range(4)); ax.set_yticks(range(4))
ax.set_xticklabels(NAMES, color='#c9d1d9', rotation=20, ha='right', fontsize=9)
ax.set_yticklabels(NAMES, color='#c9d1d9', fontsize=9)
ax.set_xlabel('Predicted', color='#8b949e', fontsize=10)
ax.set_ylabel('Actual',    color='#8b949e', fontsize=10)
ax.set_title('Confusion Matrix (v5) — per-class colour', color='white', fontsize=11, pad=8)
for sp in ax.spines.values(): sp.set_color('#30363d')

patches = [mpatches.Patch(color=CLASS_CMAPS[i](0.8), label=NAMES[i]) for i in range(4)]
ax.legend(handles=patches, loc='upper right', facecolor='#21262d',
          labelcolor='white', fontsize=8, framealpha=0.8)

ax2 = axes[1]; ax2.set_facecolor('#161b22')
BAR_COLORS = ['#58a6ff','#3fb950','#ffa657','#f778ba']
per_class_acc = [conf_mat[i,i]/max(1, conf_mat[i].sum())*100 for i in range(4)]
bars = ax2.barh(NAMES, per_class_acc, color=BAR_COLORS, edgecolor='#30363d', height=0.5)
for bar, v in zip(bars, per_class_acc):
    ax2.text(v+0.5, bar.get_y()+bar.get_height()/2,
             f'{v:.1f}%', va='center', color='#c9d1d9', fontsize=10, fontweight='bold')
avg_acc = np.mean(per_class_acc)
ax2.axvline(x=avg_acc, color='#ff7b72', lw=1.5, ls='--', alpha=0.8)
ax2.text(avg_acc+0.3, 3.6, f'Avg {avg_acc:.1f}%', color='#ff7b72', fontsize=8)
ax2.set_xlim(0, 115)
ax2.set_xlabel('Accuracy (%)', color='#8b949e', fontsize=10)
ax2.set_title('Per-Class Pose Accuracy', color='white', fontsize=11, pad=8)
ax2.tick_params(colors='#8b949e', labelsize=9)
for sp in ['top','right']: ax2.spines[sp].set_visible(False)
for sp in ['bottom','left']: ax2.spines[sp].set_color('#30363d')

fig.patch.set_facecolor('#0d1117')
plt.tight_layout(); plt.show()
print('Confusion matrix and per-class accuracy plotted')

"""## STEP 14 — Write Demo App (Gradio 5.x, PIL output, Smart routing)"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile demo/app.py
# import sys, io
# sys.path.insert(0, '/content')
# 
# import torch, torch.nn.functional as F
# import numpy as np, gradio as gr
# import matplotlib; matplotlib.use('Agg')
# import matplotlib.pyplot as plt
# import matplotlib.gridspec as gridspec
# from PIL import Image, ImageDraw
# import torchvision.transforms as T
# import traceback
# 
# from models.unet     import UNet
# from models.vit_pose import ViTPoseNet
# 
# DEVICE      = 'cuda' if torch.cuda.is_available() else 'cpu'
# IMG_SIZE    = 128
# POSE_LABELS = ['0 Upright','90 Rotated','180 Inverted','270 Rotated']
# POSE_COLORS = ['#58a6ff','#3fb950','#ffa657','#f778ba']
# MEAN = torch.tensor([0.4914,0.4822,0.4465]).view(1,3,1,1).to(DEVICE)
# STD  = torch.tensor([0.2023,0.1994,0.2010]).view(1,3,1,1).to(DEVICE)
# 
# norm_tf = T.Compose([T.Resize((IMG_SIZE,IMG_SIZE)), T.ToTensor(),
#                      T.Normalize([0.4914,0.4822,0.4465],[0.2023,0.1994,0.2010])])
# raw_tf  = T.Compose([T.Resize((IMG_SIZE,IMG_SIZE)), T.ToTensor()])
# 
# unet = UNet().to(DEVICE)
# unet.load_state_dict(torch.load('checkpoints/unet_v5_best.pth', map_location=DEVICE))
# unet.eval()
# 
# vit = ViTPoseNet(num_classes=4, pretrained=False).to(DEVICE)
# vit.load_state_dict(torch.load('checkpoints/vit_pose_v5_best.pth', map_location=DEVICE))
# vit.eval()
# 
# print(f'Models loaded | Device: {DEVICE}')
# 
# def fig_to_numpy(fig):
#     buf = io.BytesIO()
#     fig.savefig(buf, format='png', dpi=120,
#                 bbox_inches='tight', facecolor=fig.get_facecolor())
#     buf.seek(0)
#     arr = np.array(Image.open(buf).convert('RGB'))
#     buf.close()
#     plt.close(fig)
#     return arr
# 
# def is_occluded(pil_img, threshold=0.08):
#     t   = raw_tf(pil_img.resize((IMG_SIZE,IMG_SIZE)))
#     pct = (t.mean(0) < 0.08).float().mean().item()
#     return pct > threshold, round(pct*100, 1)
# 
# def apply_occlusion_pct(pil_img, pct):
#     img  = pil_img.copy(); draw = ImageDraw.Draw(img)
#     w, h = img.size
#     target = (pct/100.0)*w*h; covered = 0
#     rng = np.random.default_rng(42)
#     while covered < target:
#         bw = int(rng.integers(max(8,w//12), max(16,w//3)))
#         bh = int(rng.integers(max(8,h//12), max(16,h//3)))
#         x1 = int(rng.integers(0, max(1,w-bw+1)))
#         y1 = int(rng.integers(0, max(1,h-bh+1)))
#         draw.rectangle([x1,y1,x1+bw,y1+bh], fill=(0,0,0))
#         covered += bw*bh
#     return img
# 
# def get_probs(tensor_img):
#     with torch.no_grad():
#         r224   = F.interpolate(tensor_img, 224, mode='bilinear', align_corners=False)
#         r_norm = (r224 - MEAN) / STD
#         return F.softmax(vit(r_norm), dim=1).cpu().numpy()[0]
# 
# def run_pipeline(img_np, force_occlude, occ_pct):
#     if img_np is None:
#         return np.zeros((480,900,3), dtype=np.uint8), 'Please upload an image first.'
#     try:
#         img_pil       = Image.fromarray(img_np.astype('uint8')).convert('RGB')
#         display_input = apply_occlusion_pct(img_pil, int(occ_pct)) if force_occlude else img_pil
#         occluded, dark_pct = is_occluded(display_input)
# 
#         if occluded:
#             inp = norm_tf(display_input).unsqueeze(0).to(DEVICE)
#             with torch.no_grad():
#                 completed = unet(inp)
#             disp     = F.interpolate(completed, 256, mode='bicubic', align_corners=False)
#             recon_np = (disp[0].clamp(0,1).permute(1,2,0).cpu().numpy()*255).astype('uint8')
#             stage     = f'OCCLUDED ({dark_pct}% dark) — U-Net used'
#             stage_col = '#ff7b72'
#             stage_note= 'Smart route: U-Net reconstruction then ViT'
#         else:
#             completed  = raw_tf(display_input).unsqueeze(0).to(DEVICE)
#             recon_np   = np.array(display_input.resize((256,256)))
#             stage      = f'CLEAN ({dark_pct}% dark) — U-Net skipped'
#             stage_col  = '#3fb950'
#             stage_note = 'Smart route: direct ViT inference'
# 
#         probs_before = get_probs(norm_tf(display_input).unsqueeze(0).to(DEVICE))
#         probs_after  = get_probs(completed)
#         pred_before  = int(probs_before.argmax())
#         pred_after   = int(probs_after.argmax())
# 
#         orig_disp  = np.array(img_pil.resize((256,256)))
#         input_disp = np.array(display_input.resize((256,256)))
# 
#         fig = plt.figure(figsize=(20,8), facecolor='#0d1117')
#         gs  = gridspec.GridSpec(2, 4, figure=fig,
#                                 hspace=0.50, wspace=0.32,
#                                 left=0.03, right=0.97, top=0.91, bottom=0.05)
#         fig.suptitle('OcclusionPoseNet v5 — Smart Pipeline',
#                      color='white', fontsize=13, fontweight='bold', y=0.97)
# 
#         # Row 0 — images
#         for ai,(arr,ttl,bc) in enumerate([
#             (orig_disp,  'Original Upload','#58a6ff'),
#             (input_disp, 'Pipeline Input', '#ffa657'),
#             (recon_np,   'U-Net Output',   '#3fb950'),
#         ]):
#             ax = fig.add_subplot(gs[0,ai])
#             ax.set_facecolor('#161b22'); ax.imshow(arr); ax.axis('off')
#             ax.set_title(ttl, color=bc, fontsize=10, pad=6)
#             for sp in ax.spines.values():
#                 sp.set_edgecolor(bc); sp.set_linewidth(2)
# 
#         # Row 0 col 3 — decision panel
#         ax_s = fig.add_subplot(gs[0,3])
#         ax_s.set_facecolor('#161b22'); ax_s.axis('off')
#         for txt,y,col,sz,fw in [
#             (stage,      0.82, stage_col,              9,  'bold'),
#             (stage_note, 0.60, '#8b949e',              8,  'normal'),
#             (f'Pose: {POSE_LABELS[pred_after]}', 0.38, POSE_COLORS[pred_after], 11, 'bold'),
#             (f'Confidence: {probs_after[pred_after]*100:.1f}%', 0.18, '#c9d1d9', 9, 'normal'),
#         ]:
#             ax_s.text(0.5, y, txt, ha='center', color=col,
#                       fontsize=sz, fontweight=fw, transform=ax_s.transAxes)
#         ax_s.set_title('Pipeline Decision', color='#c9d1d9', fontsize=10, pad=6)
# 
#         # Row 1 — pose confidence charts
#         for ai,(probs_,ttl,c,hl) in enumerate([
#             (probs_before,'Pose — Before Routing','#ffa657',pred_before),
#             (probs_after, 'Pose — After Routing', '#3fb950',pred_after),
#         ]):
#             ax = fig.add_subplot(gs[1,ai*2:(ai+1)*2])
#             ax.set_facecolor('#161b22')
#             clrs = [POSE_COLORS[i] if i==hl else '#30363d' for i in range(4)]
#             bars = ax.barh(POSE_LABELS, probs_*100, color=clrs,
#                            edgecolor='#8b949e', height=0.55)
#             for bar,v in zip(bars, probs_*100):
#                 ax.text(v+0.5, bar.get_y()+bar.get_height()/2,
#                         f'{v:.1f}%', va='center', color='#c9d1d9', fontsize=9)
#             ax.set_xlim(0,115); ax.set_xlabel('Confidence (%)', color='#8b949e', fontsize=8)
#             ax.set_title(ttl, color=c, fontsize=10, pad=6)
#             ax.tick_params(colors='#8b949e', labelsize=9)
#             for sp in ['top','right']:   ax.spines[sp].set_visible(False)
#             for sp in ['bottom','left']: ax.spines[sp].set_color('#30363d')
# 
#         fig.patch.set_facecolor('#0d1117')
#         out_arr = fig_to_numpy(fig)
# 
#         improve = float((probs_after[pred_after]-probs_before[pred_before])*100)
#         report  = (
#             '## Pipeline Report\n\n'
#             f'**Stage:** {stage}\n\n'
#             '| | Pose | Confidence |\n|---|---|---|\n'
#             f'| Before | {POSE_LABELS[pred_before]} | {probs_before[pred_before]*100:.1f}% |\n'
#             f'| After  | {POSE_LABELS[pred_after]}  | {probs_after[pred_after]*100:.1f}%  |\n\n'
#             f'**Confidence change: {improve:+.1f}%**'
#         )
#         return out_arr, report
# 
#     except Exception:
#         return np.zeros((200,400,3), dtype=np.uint8), f'Error:\n```\n{traceback.format_exc()}\n```'
# 
# with gr.Blocks(title='OcclusionPoseNet v5', theme=gr.themes.Base()) as demo:
#     gr.Markdown('# OcclusionPoseNet v5 — Smart Pipeline')
#     gr.Markdown('Upload any image. Auto-detects occlusion, reconstructs and estimates pose.')
#     with gr.Row():
#         with gr.Column(scale=1):
#             inp       = gr.Image(label='Upload Image', type='numpy', height=300)
#             force_occ = gr.Checkbox(label='Force Synthetic Occlusion', value=False)
#             occ_pct   = gr.Slider(10, 70, value=30, step=5, label='Occlusion % (if forced)')
#             btn       = gr.Button('Run Smart Pipeline', variant='primary', size='lg')
#         with gr.Column(scale=2):
#             out_img = gr.Image(label='Pipeline Output', type='numpy', height=580)
#             out_txt = gr.Markdown()
#     btn.click(run_pipeline, [inp, force_occ, occ_pct], [out_img, out_txt])
# 
# if __name__ == '__main__':
#     demo.launch(share=True)
# 
# print('demo/app.py written')

"""## STEP 15 — Launch Demo"""

import subprocess, threading, time

subprocess.run(['pkill','-f','demo/app.py'], capture_output=True)
time.sleep(3)

def run_app():
    subprocess.run(['python','demo/app.py'])

threading.Thread(target=run_app, daemon=True).start()
time.sleep(20)
from google.colab.output import eval_js
url = eval_js('google.colab.kernel.proxyPort(7860)')
print(f'Demo URL: {url}')

"""## STEP 16 — Next Session: One-Cell Resume
> Run Steps 1–5 (install + write files), then run this cell to restore weights and go to Step 15.
"""

from google.colab import drive
drive.mount('/content/drive')
import os, shutil

DRIVE = '/content/drive/MyDrive/OcclusionPoseNet_v5'
pairs = [
    (f'{DRIVE}/checkpoints/unet_v5_best.pth',     'checkpoints/unet_v5_best.pth'),
    (f'{DRIVE}/checkpoints/vit_pose_v5_best.pth', 'checkpoints/vit_pose_v5_best.pth'),
    (f'{DRIVE}/results/unet_history.json',         'results/unet_history.json'),
    (f'{DRIVE}/results/vit_history.json',          'results/vit_history.json'),
]
for src, dst in pairs:
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    if os.path.exists(src):
        shutil.copy(src, dst)
        print(f'Restored: {os.path.basename(dst)}')
    else:
        print(f'Not on Drive: {os.path.basename(src)} - train first')

print('\nAll weights restored! Run Step 15 to launch demo.')